DECLARE
   v_ID SEGMERCADO.ID%type := 3;
   v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Esportistas';
BEGIN
   INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, upper(v_DESCRICAO));
   COMMIT;
END;

SELECT * FROM SEGMERCADO;