
SELECT * FROM TB_CLIENTES;

SELECT * FROM TB_CLIENTES WHERE IDADE = 22;

SELECT * FROM TB_CLIENTES WHERE IDADE > 22;

SELECT * FROM TB_CLIENTES WHERE IDADE < 22;

SELECT * FROM TB_CLIENTES WHERE IDADE <= 22;

SELECT * FROM TB_CLIENTES WHERE IDADE <> 22;

SELECT * FROM TB_CLIENTES WHERE NOME >= 'Fernando Cavalcante';

SELECT * FROM TB_CLIENTES WHERE NOME <> 'Fernando Cavalcante';

SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA >= 16.008

SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA = 16.008

SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA <> 16.008


