/*
DECLARE
  ...
BEGIN
  ...
EXCEPTION  
  WHEN NOME_DA_EXCECAO THEN
    RELACAO_COMANDOS;
  WHEN NOME_DA_EXCECAO THEN
    RELACAO_COMANDOS;
  ...
END;
*/

DECLARE
 V_RA ALUNO.RA%TYPE := '555666777';
 V_NOME ALUNO.NOME%TYPE;
BEGIN
 SELECT NOME
  INTO V_NOME
  FROM ALUNO
  WHERE RA = V_RA;
 DBMS_OUTPUT.PUT_LINE(V_RA ||' - '|| V_NOME)
EXCEPTION
 WHEN NO_DATA_FOUND THEN
  DBMS_OUTPUT.PUT_LINE ('Não há nenhum aluno com este RA');
 WHEN TOO_MANY_ROWS THEN
  DBMS_OUTPUT.PUT_LINE ('Há mais de um aluno com este RA');
END;
/

DECLARE
 V_CONTA NUMBER(3);
 TURMA_CHEIA EXCEPTION;
BEGIN
 SELECT COUNT(RA) INTO V_CONTA FROM ALUNO;
 IF V_CONTA > 10 THEN 
  RAISE TURMA_CHEIA;
 ELSE 
  DBMS_OUTPUT.PUT_LINE('Turma está com ' || V_CONTA || ' ALUNOS');
 END IF;
EXCEPTION
 WHEN TURMA_CHEIA THEN
  DBMS_OUTPUT.PUT_LINE('Não foi possível incluir: turma cheia');
END;
/

