CREATE OR REPLACE FUNCTION FUNC_SOMA (
  V_1 IN NUMBER,
  V_2 IN NUMBER)
  RETURN NUMBER 
  IS
  --SOMA NUMBER;
  BEGIN
    --SOMA := V_1 + V_2;
    --RETURN SOMA;
    RETURN (V_1 + V_2);
    
  END FUNC_SOMA;
/

SELECT FUNC_SOMA(20, 56) FROM DUAL;

BEGIN 
  soma(10, 50);
END;