CREATE TABLE TB_PRODUTO (
    PRODUTO VARCHAR2(10) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    EMBALAGEM VARCHAR2(50),
    TAMANHO VARCHAR2(50),
    SABOR VARCHAR2(30),
    PRECO_LISTA NUMBER(5,2)
)