
SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS WHERE PRODUTO = '1037797';

SELECT * FROM TB_CLIENTES WHERE CIDADE = 'Rio de Janeiro';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Laranja';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Limão';

UPDATE TB_PRODUTOS SET SABOR = 'Cítricos' WHERE PRODUTO = '1088126';
UPDATE TB_PRODUTOS SET SABOR = 'Cítricos' WHERE PRODUTO = '544931';
UPDATE TB_PRODUTOS SET SABOR = 'Cítricos' WHERE PRODUTO = '544931';

UPDATE TB_PRODUTOS SET SABOR = 'Cítricos' WHERE SABOR = 'Limão';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Cítricos';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Limão';

