-- Usar exatamento o mesmo nome 
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS WHERE OBJECT_NAME = 'SOMA';

--Usar exatamente o mesmo nome
SELECT TEXT FROM USER_SOURCE
WHERE NAME = 'PEGA_SOMA' ORDER BY LINE;

SHOW ERRORS PROCEDURE SOMA;

DROP PROCEDURE NOME_DA_PROCEDURE;
