SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE HelloWorld
AS
BEGIN
  dbms_output.put_line('Hello World!');
END HelloWorld;
/

execute HelloWorld

/
CREATE OR REPLACE PROCEDURE TESTE IS
BEGIN
 DBMS_OUTPUT.PUT_LINE('TESTANDO PROCEDURES SEM PARÂMETROS');
END TESTE;
/
execute teste;

CREATE OR REPLACE PROCEDURE SOMA (
 P_1 IN NUMBER,
 P_2 IN NUMBER) IS
BEGIN
 DBMS_OUTPUT.PUT_LINE(P_1||'+'||P_2);

END SOMA;
/
execute SOMA( 2,5);
