CREATE DATABASE EMPRESA;
GO
USE EMPRESA;
GO
CREATE TABLE FUNCIONARIO (
    ID SMALLINT PRIMARY KEY,
    Nome CHARACTER,
    CPF CHAR(11),
    Logradouro CHARACTER,
    Bairro CHARACTER,
    Cidade CHARACTER,
    CEP CHARACTER,
    UF CHAR,
    Cargo CHARACTER,
    FK_CONJUGE_ID SMALLINT
);
GO
CREATE TABLE DEPENDENTE (
    IDFunc SMALLINT,
    Nome CHARACTER,
    CPF CHAR
);
GO
CREATE TABLE CONJUGE (
    ID SMALLINT PRIMARY KEY,
    Nome CHARACTER,
    IDFunc SMALLINT,
    CPF CHAR
);
GO
ALTER TABLE CONJUGE ADD CONSTRAINT FK_FUNCIONARIO2
	FOREIGN KEY (IDFunc)
	REFERENCES FUNCIONARIO (ID)
	ON DELETE CASCADE;
