
SELECT TO_DATE('12/11/2019', 'DD/MM/YYYY') FROM DUAL;

SELECT TO_DATE('12/11/2019', 'MM/DD/YYYY') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'MM/DD/YYYY HH12:MM:SS AM') FROM DUAL;

SELECT EXTRACT(MONTH FROM TO_DATE('12/11/2019', 'DD/MM/YYYY')) FROM DUAL;

SELECT EXTRACT(MONTH FROM TO_DATE('12/11/2019', 'MM/DD/YYYY')) FROM DUAL;

SELECT TO_NUMBER('10') + 100 FROM DUAL;

SELECT TO_CHAR(10, '00000') FROM DUAL;

SELECT NVL(10,0) FROM DUAL;

SELECT TABELA_DE_VENDEDORES.NOME AS NOME_VENDEDOR
, TABELA_DE_VENDEDORES.BAIRRO AS BAIRRO_VENDEDOR
, TABELA_DE_CLIENTES.NOME AS NOME_CLIENTE
, TABELA_DE_CLIENTES.BAIRRO AS BAIRRO_CLIENTE
FROM TABELA_DE_VENDEDORES
FULL JOIN TABELA_DE_CLIENTES
ON TABELA_DE_VENDEDORES.BAIRRO = TABELA_DE_CLIENTES.BAIRRO;

SELECT NVL(TABELA_DE_VENDEDORES.NOME, 'Vendedor Vazio') AS NOME_VENDEDOR
, TABELA_DE_VENDEDORES.BAIRRO AS BAIRRO_VENDEDOR
, TABELA_DE_CLIENTES.NOME AS NOME_CLIENTE
, TABELA_DE_CLIENTES.BAIRRO AS BAIRRO_CLIENTE
FROM TABELA_DE_VENDEDORES
FULL JOIN TABELA_DE_CLIENTES
ON TABELA_DE_VENDEDORES.BAIRRO = TABELA_DE_CLIENTES.BAIRRO;

SELECT GREATEST(10,20,15) FROM DUAL;

SELECT * FROM TABELA_DE_CLIENTES;

SELECT VOLUME_DE_COMPRA, LIMITE_DE_CREDITO, 
GREATEST(VOLUME_DE_COMPRA,LIMITE_DE_CREDITO) FROM TABELA_DE_CLIENTES;




