SET SERVEROUTPUT ON;

CREATE OR REPLACE PACKAGE PACK_ALUNO IS
 PROCEDURE ADICIONA_ALUNO (V_RA IN ALUNO.RA%TYPE,
  V_NOME IN ALUNO.NOME%TYPE,
  V_SNOME IN ALUNO.SOBRENOME%TYPE);
 PROCEDURE ATUALIZA_NOME_ALUNO (V_RA IN ALUNO.RA%TYPE,
  V_NOME IN ALUNO.NOME%TYPE);
END PACK_ALUNO;
/

CREATE OR REPLACE PACKAGE BODY PACK_ALUNO IS
 PROCEDURE ADICIONA_ALUNO
 (V_RA IN ALUNO.RA%TYPE,
  V_NOME IN ALUNO.NOME%TYPE,
  V_SNOME IN ALUNO.SOBRENOME%type)
 IS
 BEGIN
    INSERT INTO ALUNO(RA, NOME, SOBRENOME)
    VALUES (V_RA, V_NOME, V_SNOME);
  
    IF SQL%NOTFOUND THEN
      dbms_output.put_line('Não houve inserção');
    ELSE
      dbms_output.put_line('Inserido com sucesso');
    END IF;
 EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
   DBMS_OUTPUT.PUT_LINE('RA já cadastrado');
 END ADICIONA_ALUNO;
 
 PROCEDURE ATUALIZA_NOME_ALUNO
 (V_RA IN ALUNO.RA%TYPE,
  V_NOME IN ALUNO.NOME%TYPE)
 IS
 BEGIN
  UPDATE ALUNO SET NOME = V_NOME
  WHERE RA = V_RA;
  
  IF SQL%NOTFOUND THEN
    dbms_output.put_line('Não houve alteração');
  ELSE
    dbms_output.put_line('Nome atualizado');
  END IF;
  
 EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
   DBMS_OUTPUT.PUT_LINE('Aluno atualizado');
 END ATUALIZA_NOME_ALUNO;
 
END PACK_ALUNO;
/

EXEC PACK_ALUNO.ADICIONA_ALUNO ('9996662288','Arroz','Douce');
