-- ================
-- SISTEMA BARBEARIA - ORACLE SQL
-- ================
-- Este script cria um sistema completo para gerenciamento de uma barbearia
-- incluindo clientes, barbeiros, serviços e agendamentos.
--
-- Autor: Exemplo educacional
-- Data: 2024
-- SGBD: Oracle Database
--

-- ================
-- LIMPEZA INICIAL (OPCIONAL)
-- ================
-- Descomente as linhas abaixo se precisar recriar as tabelas
/*
DROP TABLE agendamento_servicos CASCADE CONSTRAINTS;
DROP TABLE agendamentos CASCADE CONSTRAINTS;
DROP TABLE servicos CASCADE CONSTRAINTS;
DROP TABLE barbeiros CASCADE CONSTRAINTS;
DROP TABLE clientes CASCADE CONSTRAINTS;

DROP SEQUENCE seq_clientes;
DROP SEQUENCE seq_barbeiros;
DROP SEQUENCE seq_servicos;
DROP SEQUENCE seq_agendamentos;
*/

-- ================
-- CRIAÇÃO DAS SEQUENCES
-- ================

CREATE SEQUENCE seq_clientes
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCACHE;

CREATE SEQUENCE seq_barbeiros
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCACHE;

CREATE SEQUENCE seq_servicos
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCACHE;

CREATE SEQUENCE seq_agendamentos
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCACHE;

-- ================
-- TABELA CLIENTES
-- ================
CREATE TABLE clientes (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR2(120) NOT NULL,
    telefone   VARCHAR2(25),
    email      VARCHAR2(120),
    data_cadastro DATE DEFAULT SYSDATE,
    ativo      CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N')),
    
    CONSTRAINT uk_clientes_email UNIQUE (email),
    CONSTRAINT chk_clientes_nome CHECK (LENGTH(nome) >= 2),
    CONSTRAINT chk_clientes_email CHECK (email LIKE '%_@_%._%')
);

-- Comentários explicativos
COMMENT ON TABLE clientes IS 'Armazena informações dos clientes da barbearia';
COMMENT ON COLUMN clientes.id IS 'Identificador único do cliente (chave primária)';
COMMENT ON COLUMN clientes.nome IS 'Nome completo do cliente';
COMMENT ON COLUMN clientes.telefone IS 'Telefone para contato';
COMMENT ON COLUMN clientes.email IS 'Email único do cliente';
COMMENT ON COLUMN clientes.data_cadastro IS 'Data de cadastro do cliente';
COMMENT ON COLUMN clientes.ativo IS 'Status do cliente (S-Ativo, N-Inativo)';

-- ================
-- TABELA BARBEIROS
-- ================
CREATE TABLE barbeiros (
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR2(120) NOT NULL,
    telefone VARCHAR2(25),
    especialidade VARCHAR2(100),
    data_admissao DATE DEFAULT SYSDATE,
    ativo CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N')),
    
    CONSTRAINT chk_barbeiros_nome CHECK (LENGTH(nome) >= 2)
);

-- Comentários explicativos
COMMENT ON TABLE barbeiros IS 'Armazena informações dos barbeiros da barbearia';
COMMENT ON COLUMN barbeiros.id IS 'Identificador único do barbeiro (chave primária)';
COMMENT ON COLUMN barbeiros.nome IS 'Nome completo do barbeiro';
COMMENT ON COLUMN barbeiros.telefone IS 'Telefone do barbeiro';
COMMENT ON COLUMN barbeiros.especialidade IS 'Especialidade do barbeiro (corte, barba, etc.)';
COMMENT ON COLUMN barbeiros.data_admissao IS 'Data de admissão do barbeiro';
COMMENT ON COLUMN barbeiros.ativo IS 'Status do barbeiro (S-Ativo, N-Inativo)';

-- ================
-- TABELA SERVICOS
-- ================
CREATE TABLE servicos (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR2(100) NOT NULL,
    descricao    VARCHAR2(500),
    duracao_min  NUMBER NOT NULL,
    preco        NUMBER(8,2) DEFAULT 0,
    ativo        CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N')),
    
    CONSTRAINT uk_servicos_nome UNIQUE (nome),
    CONSTRAINT chk_servicos_duracao CHECK (duracao_min > 0 AND duracao_min <= 480),
    CONSTRAINT chk_servicos_preco CHECK (preco >= 0),
    CONSTRAINT chk_servicos_nome CHECK (LENGTH(nome) >= 3)
);

-- Comentários explicativos
COMMENT ON TABLE servicos IS 'Catálogo de serviços oferecidos pela barbearia';
COMMENT ON COLUMN servicos.id IS 'Identificador único do serviço (chave primária)';
COMMENT ON COLUMN servicos.nome IS 'Nome do serviço (único)';
COMMENT ON COLUMN servicos.descricao IS 'Descrição detalhada do serviço';
COMMENT ON COLUMN servicos.duracao_min IS 'Duração do serviço em minutos (máx. 8 horas)';
COMMENT ON COLUMN servicos.preco IS 'Preço do serviço';
COMMENT ON COLUMN servicos.ativo IS 'Status do serviço (S-Ativo, N-Inativo)';

-- ================
-- TABELA AGENDAMENTOS
-- ================
CREATE TABLE agendamentos (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id  NUMBER NOT NULL,
    barbeiro_id NUMBER NOT NULL,
    inicio      TIMESTAMP NOT NULL,
    fim         TIMESTAMP,
    status      VARCHAR2(15) DEFAULT 'MARCADO' NOT NULL,
    observacoes VARCHAR2(500),
    valor_total NUMBER(8,2) DEFAULT 0,
    data_criacao TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT fk_ag_cli FOREIGN KEY (cliente_id)  REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_ag_bar FOREIGN KEY (barbeiro_id) REFERENCES barbeiros(id),
    CONSTRAINT chk_ag_status CHECK (status IN ('MARCADO','CANCELADO','CONCLUIDO','EM_ANDAMENTO')),
    CONSTRAINT chk_ag_datas CHECK (fim IS NULL OR fim > inicio),
    CONSTRAINT chk_ag_valor CHECK (valor_total >= 0),
    CONSTRAINT chk_ag_inicio CHECK (inicio > SYSTIMESTAMP - INTERVAL '1' DAY) -- Não pode agendar no passado
);

-- Comentários explicativos
COMMENT ON TABLE agendamentos IS 'Agendamentos de serviços dos clientes';
COMMENT ON COLUMN agendamentos.id IS 'Identificador único do agendamento (chave primária)';
COMMENT ON COLUMN agendamentos.cliente_id IS 'Referência ao cliente (chave estrangeira)';
COMMENT ON COLUMN agendamentos.barbeiro_id IS 'Referência ao barbeiro (chave estrangeira)';
COMMENT ON COLUMN agendamentos.inicio IS 'Data e hora de início do agendamento';
COMMENT ON COLUMN agendamentos.fim IS 'Data e hora de fim do agendamento (calculada)';
COMMENT ON COLUMN agendamentos.status IS 'Status do agendamento';
COMMENT ON COLUMN agendamentos.observacoes IS 'Observações adicionais do agendamento';
COMMENT ON COLUMN agendamentos.valor_total IS 'Valor total do agendamento';
COMMENT ON COLUMN agendamentos.data_criacao IS 'Data de criação do agendamento';

-- ================
-- TABELA AGENDAMENTO_SERVICOS (Relacionamento N:M)
-- ================
CREATE TABLE agendamento_servicos (
    agendamento_id NUMBER NOT NULL,
    servico_id     NUMBER NOT NULL,
    quantidade     NUMBER DEFAULT 1 NOT NULL,
    preco_unitario NUMBER(8,2),
    observacoes    VARCHAR2(200),
    
    PRIMARY KEY (agendamento_id, servico_id),
    CONSTRAINT fk_as_ag FOREIGN KEY (agendamento_id) REFERENCES agendamentos(id) ON DELETE CASCADE,
    CONSTRAINT fk_as_sv FOREIGN KEY (servico_id)     REFERENCES servicos(id),
    CONSTRAINT chk_as_qtd CHECK (quantidade > 0),
    CONSTRAINT chk_as_preco CHECK (preco_unitario IS NULL OR preco_unitario >= 0)
);

-- Comentários explicativos
COMMENT ON TABLE agendamento_servicos IS 'Relacionamento entre agendamentos e serviços (N:M)';
COMMENT ON COLUMN agendamento_servicos.agendamento_id IS 'Referência ao agendamento';
COMMENT ON COLUMN agendamento_servicos.servico_id IS 'Referência ao serviço';
COMMENT ON COLUMN agendamento_servicos.quantidade IS 'Quantidade do serviço no agendamento';
COMMENT ON COLUMN agendamento_servicos.preco_unitario IS 'Preço unitário na data do agendamento';
COMMENT ON COLUMN agendamento_servicos.observacoes IS 'Observações específicas do serviço no agendamento';

-- ================
-- ÍNDICES PARA OTIMIZAÇÃO
-- ================

-- Índices para consultas frequentes por cliente e data
CREATE INDEX idx_ag_cliente_data  ON agendamentos (cliente_id, inicio);

-- Índices para consultas frequentes por barbeiro e data
CREATE INDEX idx_ag_barbeiro_data ON agendamentos (barbeiro_id, inicio);

-- Índice para consultas por status
CREATE INDEX idx_ag_status ON agendamentos (status);

-- Índice para consultas por data de criação
CREATE INDEX idx_ag_data_criacao ON agendamentos (data_criacao);

-- Índice para email dos clientes (login/busca)
CREATE INDEX idx_clientes_email ON clientes (email);

-- Índice para nome dos clientes (busca)
CREATE INDEX idx_clientes_nome ON clientes (UPPER(nome));

-- ================
-- COMENTÁRIOS FINAIS
-- ================

COMMENT ON TABLE agendamento_servicos IS 'Tabela de junção que permite que um agendamento tenha múltiplos serviços e um serviço apareça em múltiplos agendamentos. Implementa relacionamento N:M com informações adicionais.';

-- Exibir mensagem de sucesso
SELECT 'Estrutura do banco de dados BARBEARIA criada com sucesso!' AS status FROM dual;
SELECT 'Tabelas: CLIENTES, BARBEIROS, SERVICOS, AGENDAMENTOS, AGENDAMENTO_SERVICOS' AS tabelas_criadas FROM dual;
SELECT 'Próximo passo: Execute o script 02-inserir-dados.sql' AS proximo_passo FROM dual;