
SELECT NOME FROM TABELA_DE_CLIENTES;

SELECT NOME, UPPER(NOME) FROM TABELA_DE_CLIENTES;

SELECT NOME, LOWER(NOME) FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO, INITCAP(NOME_DO_PRODUTO) FROM TABELA_DE_PRODUTOS;

SELECT CONCAT(ENDERECO_1, BAIRRO) FROM TABELA_DE_CLIENTES;

SELECT NOME, 'Endereço: ' || ENDERECO_1 || ' ' || BAIRRO || ' ' || CIDADE || ' ' || ESTADO || ', CEP: ' || CEP
FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO, LPAD(NOME_DO_PRODUTO, 60, '*') FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, RPAD(NOME_DO_PRODUTO, 60, '*') FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, SUBSTR(NOME_DO_PRODUTO,3,5) FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, INSTR(NOME_DO_PRODUTO, '-') FROM TABELA_DE_PRODUTOS;

SELECT LTRIM('           AAAAAAA') FROM DUAL;

SELECT RTRIM('AAAAAAA         ') FROM DUAL;

SELECT NOME_DO_PRODUTO, REPLACE(REPLACE(NOME_DO_PRODUTO, 'Litro', 'L'),'Ls','L') FROM TABELA_DE_PRODUTOS;

