
CREATE PROCEDURE CalculaIdade
AS
BEGIN
   UPDATE [TABELA DE CLIENTES] SET IDADE = DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE())
END

INSERT INTO [TABELA DE CLIENTES] (CPF, [NOME], [ENDERECO 1], BAIRRO, CIDADE, ESTADO, CEP, [DATA DE NASCIMENTO],
SEXO, [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA])
VALUES
('123123123','JOÃO MACHADO', 'RUA PROJETADA A','MADUREIRA','Rio de Janeiro','RJ','20000',
'20000306','M',120000, 120000, 120000)

SELECT * FROM [TABELA DE CLIENTES] WHERE CPF = '123123123'
EXEC CalculaIdade



