
SELECT * FROM [VENDEDORES]

BEGIN TRANSACTION

UPDATE [VENDEDORES] SET [COMISSÃO] = [COMISSÃO] * 1.15

INSERT INTO [VENDEDORES] ([MATRÍCULA], [NOME], [BAIRRO],[COMISSÃO], [DATA ADMISSÃO], [FÉRIAS])
VALUES ('99999','João da Silva','Icaraí',0.08,'2014-09-01',0)

ROLLBACK

COMMIT

