
SELECT COUNT(*) FROM TABELA_DE_CLIENTES;

SELECT CPF, COUNT(*) FROM NOTAS_FISCAIS GROUP BY CPF;

SELECT DISTINCT A.CPF AS CPF_DO_CADASTRO
, A.NOME, B.CPF AS CPF_DA_NOTA 
FROM TABELA_DE_CLIENTES A LEFT JOIN NOTAS_FISCAIS B
ON A.CPF = B.CPF
WHERE B.CPF IS NULL;


SELECT DISTINCT A.CPF AS CPF_DO_CADASTRO
, A.NOME, B.CPF AS CPF_DA_NOTA 
FROM NOTAS_FISCAIS B RIGHT JOIN TABELA_DE_CLIENTES A
ON A.CPF = B.CPF
WHERE B.CPF IS NULL;