SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS WHERE OBJECT_NAME = 'NOME_DA_PROCEDURE';

SELECT TEXT FROM USER_SOURCE
WHERE NAME = 'NOME_DA_PROCEDURE' ORDER BY LINE;

SHOW ERRORS PROCEDURE NOME_DA_PROCEDURE;

DROP PROCEDURE NOME_DA_PROCEDURE;
