
SELECT * FROM TABELA_DE_CLIENTES;

SELECT ESTADO, LIMITE_DE_CREDITO FROM TABELA_DE_CLIENTES;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS TOTAL_CREDITO FROM TABELA_DE_CLIENTES GROUP BY ESTADO;

SELECT EMBALAGEM, PRECO_DE_LISTA FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS NUMERO_PRODUTOS FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT BAIRRO, SUM(LIMITE_DE_CREDITO) AS TOTAL_CREDITO FROM TABELA_DE_CLIENTES GROUP BY BAIRRO;

SELECT BAIRRO, SUM(LIMITE_DE_CREDITO) AS TOTAL_CREDITO FROM TABELA_DE_CLIENTES 
WHERE CIDADE = 'Rio de Janeiro' GROUP BY BAIRRO;

SELECT ESTADO, BAIRRO, SUM(LIMITE_DE_CREDITO) AS TOTAL_CREDITO FROM
TABELA_DE_CLIENTES GROUP BY ESTADO, BAIRRO ORDER BY ESTADO, BAIRRO;


