  --Drop the table
  DROP TABLE TRANSACTIONS;
  
  --Create the table
  CREATE TABLE "SYSTEM"."TRANSACTIONS" 
      ("STOCK_ID"           NUMBER(*,0), 
       "TIME_ID"            NUMBER(*,0), 
       "BROKERAGE_ID"       NUMBER(*,0), 
       "BUY_SELL_INDICATOR" CHAR(1 BYTE), 
       "NUMBER_SHARES"      NUMBER(*,0), 
       "PRICE"              FLOAT(4) DEFAULT 0
      ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
          PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 
          BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  --Test whether there is any data
  SELECT * FROM TRANSACTIONS;
  
  COMMIT;