
SELECT X.SABOR, X.ANO, CONVERT(DECIMAL(10,2), X.FATURAMENTO) AS FATURAMENTO, CONVERT(VARCHAR, (X.FATURAMENTO/ Y.FATURAMENTO_TOTAL) * 100 )+ '%' AS PARTICIPACAO
FROM 
(SELECT A.SABOR, YEAR(C.DATA) AS ANO, SUM(B.PREÇO * B.QUANTIDADE) AS FATURAMENTO FROM 
[TABELA DE PRODUTOS] A 
INNER JOIN [ITENS NOTAS FISCAIS] B ON A.[CODIGO DO PRODUTO] = B.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO
WHERE YEAR(C.DATA) = 2016
GROUP BY A.SABOR, YEAR(C.DATA) 
) X
INNER JOIN
(SELECT YEAR(C.DATA) AS ANO, SUM(B.PREÇO * B.QUANTIDADE) AS FATURAMENTO_TOTAL FROM 
[TABELA DE PRODUTOS] A 
INNER JOIN [ITENS NOTAS FISCAIS] B ON A.[CODIGO DO PRODUTO] = B.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO
WHERE YEAR(C.DATA) = 2016
GROUP BY YEAR(C.DATA) 
) Y
ON X.ANO = Y.ANO
ORDER BY X.FATURAMENTO DESC




