CREATE OR REPLACE PACKAGE NOME_PACKAGE IS
 PROCEDURE NOME_PROCEDURE (LISTA_DE_PARAMETROS);
 FUNCTION NOME_FUNCTION (LISTA_DE_PARAMENTROS);
 --Declaração de variáveis, constantes, exceções e cursores públicos
END NOME_PACKAGE;

CREATE OR REPLACE PACKAGE BODY NOME_PACKAGE IS
  Declaração de variáveis, constantes, exceções e cursores privados
 PROCEDURE NOME_PROCEDURE (LISTA_DE_PARAMETROS)
  IS
  ...
 BEGIN
  ...
 END NOME_PROCEDURE;
 FUNCTION NOME_FUNCTION (LISTA_DE_PARAMETROS)
  RETURN TIPO_DE_DADO
  IS
  ...
 BEGIN
  ...
  RETURN
 END NOME_FUNÇÃO;
END;