
SELECT * FROM V$SYSMETRIC;

SELECT METRIC_NAME, VALUE FROM V$SYSMETRIC
WHERE METRIC_NAME IN ('Database CPU Time Ratio','Database Wait Time Ratio');

SELECT * FROM ALL_OBJECTS;

SELECT * FROM V$SYSTEM_WAIT_CLASS WHERE WAIT_CLASS <> 'Idle';

SELECT SUM(TOTAL_WAITS) AS SUM_TOTAL_WAITS, SUM(TIME_WAITED) AS SUM_TIME_WAITED
FROM V$SYSTEM_WAIT_CLASS WHERE WAIT_CLASS <> 'Idle';

SELECT A.WAIT_CLASS, ROUND(100*(A.TOTAL_WAITS/B.SUM_TOTAL_WAITS),2) AS PCT_TOTAL_WAITS,
ROUND(100*(A.TIME_WAITED/B.SUM_TIME_WAITED),2) AS PCT_TIME_WAITED FROM
(SELECT * FROM V$SYSTEM_WAIT_CLASS WHERE WAIT_CLASS <> 'Idle') A,
(SELECT SUM(TOTAL_WAITS) AS SUM_TOTAL_WAITS, SUM(TIME_WAITED) AS SUM_TIME_WAITED
FROM V$SYSTEM_WAIT_CLASS WHERE WAIT_CLASS <> 'Idle') B;
