SET SERVEROUTPUT ON;

CREATE TABLE EMPREGADOS (
  ID NUMBER NOT NULL,
  NOME VARCHAR2(50) NOT NULL,
  IDADE NUMBER(2) NOT NULL,
  SALARIO NUMERIC(10, 2)
);

--DROP TABLE EMPREGADOS
INSERT INTO EMPREGADOS
  VALUES (1, 'ANA', 25, 5000);
INSERT INTO EMPREGADOS
  VALUES (1, 'JOAO', 21, 2000);
INSERT INTO EMPREGADOS
  VALUES (1, 'HELENA', 30, 3967);
  
SELECT * FROM EMPREGADOS;

-- TRIGGER PARA EXIBIR OS VALORES DE SALÁRIO

CREATE OR REPLACE TRIGGER TRG_EXIBIR_SALARIOS 
  BEFORE INSERT OR UPDATE ON EMPREGADOS
  FOR EACH ROW
WHEN (NEW.ID > 0)
DECLARE 
  DIF_SAL NUMBER;
BEGIN
  DIF_SAL := :NEW.SALARIO - :OLD.SALARIO;
  dbms_output.put_line('Salario antigo: ' || :OLD.SALARIO);
  dbms_output.put_line('Salario novo: ' || :NEW.SALARIO);
  dbms_output.put_line('Diferenca entre eles: ' || DIF_SAL);
END;
/

INSERT INTO EMPREGADOS
  VALUES (-1, 'José', 28, 4000);

-- Testando a trigger
INSERT INTO EMPREGADOS
  VALUES (5, 'Lucas', 28, 4000);
UPDATE EMPREGADOS SET SALARIO = 4100 
  WHERE ID = 5;





