
SELECT A.[CPF], A.[NOME], SUM(C.[QUANTIDADE] * C.[PREÇO]) AS FATURAMENTO
FROM [TABELA DE CLIENTES] A INNER JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF AND YEAR(B.[DATA]) = 2016
INNER JOIN [ITENS NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO
GROUP BY A.[CPF], A.[NOME]

CREATE TYPE ListaClientes as TABLE
(CPF VARCHAR(12) NOT NULL)

DECLARE @Lista AS ListaClientes
INSERT INTO @Lista (CPF) VALUES ('8502682733'), ('8719655770'), ('9283760794')
SELECT * FROM @Lista

SELECT * FROM [TABELA DE CLIENTES]


DECLARE @Lista AS ListaClientes
INSERT INTO @Lista (CPF) VALUES ('8502682733'), ('8719655770'), ('9283760794')

SELECT A.[CPF], A.[NOME], SUM(C.[QUANTIDADE] * C.[PREÇO]) AS FATURAMENTO
FROM [TABELA DE CLIENTES] A INNER JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF AND YEAR(B.[DATA]) = 2016
INNER JOIN [ITENS NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO
INNER JOIN @Lista D ON A.CPF = D.CPF
GROUP BY A.[CPF], A.[NOME]

CREATE PROCEDURE FaturamentoClientes2016
@LISTA AS ListaClientes READONLY
AS
SELECT A.[CPF], A.[NOME], SUM(C.[QUANTIDADE] * C.[PREÇO]) AS FATURAMENTO
FROM [TABELA DE CLIENTES] A INNER JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF AND YEAR(B.[DATA]) = 2016
INNER JOIN [ITENS NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO
INNER JOIN @LISTA D ON A.CPF = D.CPF
GROUP BY A.[CPF], A.[NOME]


DECLARE @Lista AS ListaClientes
INSERT INTO @Lista (CPF) VALUES ('5840119709'), ('7771579779'), ('9283760794')
EXEC FaturamentoClientes2016 @LISTA = @Lista


SELECT * FROM [TABELA DE CLIENTES]










