[<<label_name>>]
CASE [TRUE | selector]
   WHEN expression1 THEN
	sequence_of_statements1;
   WHEN expression2 THEN
	sequence_of_statements2;
   ...
   WHEN expressionN THEN
	sequence_of_statementsN;
  [ELSE sequence_of_statementsN+1;]
END CASE [label_name];

DECLARE
V_SIGLA VARCHAR2(10):= 'TBD';
V_CURSO VARCHAR2(30);
BEGIN
CASE V_SIGLA
 WHEN 'TADS' THEN
 V_CURSO := 'TECNOLOGIA EM ANÁLISE E DESENVOLVIMENTO DE SISTEMAS';
 WHEN 'TBD' THEN
 V_CURSO := 'TECNOLOGIA EM BANCO DE DADOS';
 WHEN 'TGTI' THEN
 V_CURSO := 'TECNOLOGIA EM GESTÃO DE TECNOLOGIA DA INFORMAÇÃO';
 WHEN 'TRC' THEN
 V_CURSO := 'TECNOLOGIA EM REDES DE COMPUTADORES';
 WHEN 'TSEG' THEN
 V_CURSO := 'TECNOLOGIA EM SEGURANÇA DA INFORMAÇÃO';
 WHEN 'TSIN' THEN
 V_CURSO := 'TECNOLOGIA EM SISTEMAS PARA INTERNET';
 ELSE
 V_CURSO := 'CURSO DESCONHECIDO';
END CASE;
DBMS_OUTPUT.PUT_LINE(V_SIGLA || ' – ' || V_CURSO);
END;
/

DECLARE
V_N NUMBER(2):= 15;
BEGIN
CASE
 WHEN (MOD(V_N,2) = 0) THEN
 DBMS_OUTPUT.PUT_LINE('O número ' || V_N || ' é PAR');
 WHEN (MOD(V_N,2) != 0) THEN
 DBMS_OUTPUT.PUT_LINE('O número ' || V_N || ' é ÍMPAR');
 ELSE
 DBMS_OUTPUT.PUT_LINE('Valor inválido, não é um número
inteiro.');
END CASE;
END;
/