CREATE TABLE Disciplina (
	ID INT NOT NULL,
	Disciplina NVARCHAR2(120) NOT NULL,
	CargaHoraria INT	NOT NULL,
	CONSTRAINT PK_ID_Disciplina PRIMARY KEY (ID)
);
CREATE TABLE Curso (
	ID INT NOT NULL,
	Curso NVARCHAR2(50) NOT NULL,
	CONSTRAINT PK_ID_Curso PRIMARY KEY (ID)
);
CREATE TABLE CursoDisciplina (
	ID INT NOT NULL,
	ID_Curso	INT	NOT NULL,
	ID_Disciplina	INT	NOT NULL,
	CONSTRAINT PK_ID_CursoDisciplina	PRIMARY KEY (ID),
	CONSTRAINT FK_CursoDisciplina_Curso	FOREIGN KEY (ID_Curso)
		REFERENCES Curso (ID),
	CONSTRAINT FK_CursoDisciplina_Disciplina	FOREIGN KEY (ID_Disciplina)
		REFERENCES Disciplina	(ID)
);
CREATE TABLE Boletim (
	ID INT NOT NULL,
	ID_AlunoCurso	INT NOT NULL
);
CREATE TABLE UnidadeFederativa (
	ID INT NOT NULL,
	UF CHAR(2) NOT NULL,
	Descricao VARCHAR(25) NOT NULL,
	CONSTRAINT PK_ID_UF PRIMARY KEY (ID)
);
CREATE TABLE Aluno (
	ID INT NOT NULL,
	RA CHAR(11)		NOT NULL,
	PrimeiroNome	NVARCHAR2(50) NOT NULL,
	UltimoNome	NVARCHAR2(50) NOT NULL,
	RG	CHAR(11)	NOT NULL,
	CPF CHAR(11)	NOT NULL,
	Genero	NVARCHAR2(30)	NOT NULL,
	Logradouro	NVARCHAR2(120) NOT NULL,
	Descricao	NVARCHAR2(120) NOT NULL,
	CEP		CHAR(6) NOT NULL,
	UF	CHAR(2)	NOT NULL,
	Pais	NVARCHAR2(50)	NOT NULL,
	ID_Curso	INT	NOT NULL,
	ID_Disciplina INT NOT NULL,
	-- Define a chave primária da tabela
	CONSTRAINT PK_ID_Aluno PRIMARY KEY (ID),
	CONSTRAINT FK_Aluno_Curso	FOREIGN KEY	(ID_Curso)
		REFERENCES	Curso(ID),
	CONSTRAINT FK_Aluno_Disciplina	FOREIGN KEY (ID_Disciplina)
		REFERENCES	Disciplina(ID)
);

CREATE TABLE ALUNO_GRADUACAO (
	ID INT NOT NULL,
	RA CHAR(11)		NOT NULL,
	PrimeiroNome	NVARCHAR2(50) NOT NULL,
	UltimoNome	NVARCHAR2(50) NOT NULL,
	RG	CHAR(11)	NOT NULL,
	CPF CHAR(11)	NOT NULL,
	-- Define a chave primária da tabela
	CONSTRAINT PK_ID_aluno_graduacao PRIMARY KEY (ID)
);