-- ===============================================
-- Estruturas Básicas - Sistema MusiStream
-- Módulo 04: Trabalhando com a Estrutura de Tabelas
-- ===============================================

-- Limpar estruturas anteriores se existirem
DROP TABLE IF EXISTS playlist_musica CASCADE CONSTRAINT;
DROP TABLE IF EXISTS playlist CASCADE CONSTRAINT;
DROP TABLE IF EXISTS musica CASCADE CONSTRAINT;
DROP TABLE IF EXISTS album CASCADE CONSTRAINT;
DROP TABLE IF EXISTS artista CASCADE CONSTRAINT;
DROP TABLE IF EXISTS genero_musical CASCADE CONSTRAINT;
DROP TABLE IF EXISTS usuario CASCADE CONSTRAINT;
DROP TABLE IF EXISTS configuracao_usuario CASCADE CONSTRAINT;

-- ===============================================
-- 1. USUÁRIOS
-- ===============================================

CREATE TABLE IF NOT EXISTS usuario (
    id_usuario       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_usuario     VARCHAR2(100) NOT NULL,
    sobrenome        VARCHAR2(100),
    nome_exibicao    VARCHAR2(150),
    email            VARCHAR2(254) NOT NULL UNIQUE,
    senha_hash       VARCHAR2(255) NOT NULL,
    data_nascimento  DATE,
    genero           CHAR(1),
    pais             VARCHAR2(50),
    idioma_pref      VARCHAR2(10) DEFAULT 'pt-BR',
    data_cadastro    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultima_atividade TIMESTAMP,
    ativo            NUMBER(1) DEFAULT 1 CHECK (ativo IN (0,1)),
    email_verificado NUMBER(1) DEFAULT 0 CHECK (email_verificado IN (0,1)),
    
    CHECK (genero IN ('M', 'F', 'O', 'N')),
    CHECK (LENGTH(nome_usuario) >= 2),
    CHECK (REGEXP_LIKE(email, '.+@.+\..+'))
);

COMMENT ON TABLE usuario IS 'Usuários registrados na plataforma MusiStream';

-- ===============================================
-- 2. CONFIGURAÇÕES DE USUÁRIO
-- ===============================================

CREATE TABLE IF NOT EXISTS configuracao_usuario (
    id_usuario        NUMBER PRIMARY KEY,
    tema              VARCHAR2(20) DEFAULT 'escuro',
    qualidade_audio   VARCHAR2(20) DEFAULT 'alta',
    volume_padrao     NUMBER DEFAULT 75 CHECK (volume_padrao BETWEEN 0 AND 100),
    reproducao_auto   NUMBER(1) DEFAULT 1 CHECK (reproducao_auto IN (0,1)),
    notificacoes      NUMBER(1) DEFAULT 1 CHECK (notificacoes IN (0,1)),
    modo_offline      NUMBER(1) DEFAULT 0 CHECK (modo_offline IN (0,1)),
    idioma_interface  VARCHAR2(10) DEFAULT 'pt-BR',
    
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    CHECK (tema IN ('claro','escuro','auto')),
    CHECK (qualidade_audio IN ('baixa','media','alta','lossless'))
);

-- ===============================================
-- 3. GÊNEROS MUSICAIS
-- ===============================================

CREATE TABLE IF NOT EXISTS genero_musical (
    id_genero       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_genero     VARCHAR2(50) NOT NULL UNIQUE,
    descricao       CLOB,
    genero_pai      NUMBER,
    cor_tema        VARCHAR2(7),
    icone           VARCHAR2(100),
    ativo           NUMBER(1) DEFAULT 1 CHECK (ativo IN (0,1)),
    
    FOREIGN KEY (genero_pai) REFERENCES genero_musical(id_genero),
    CHECK (LENGTH(nome_genero) >= 2),
    CHECK (cor_tema IS NULL OR REGEXP_LIKE(cor_tema, '^#[0-9A-Fa-f]{6}$'))
);

-- ===============================================
-- 4. ARTISTAS
-- ===============================================

CREATE TABLE IF NOT EXISTS artista (
    id_artista       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_artista     VARCHAR2(100) NOT NULL,
    tipo_artista     VARCHAR2(20) NOT NULL,
    biografia        CLOB,
    data_formacao    DATE,
    data_fim         DATE,
    pais_origem      VARCHAR2(50),
    cidade_origem    VARCHAR2(100),
    genero_principal NUMBER,
    website          VARCHAR2(255),
    instagram        VARCHAR2(100),
    twitter          VARCHAR2(100),
    facebook         VARCHAR2(255),
    spotify_id       VARCHAR2(50),
    imagem_perfil    VARCHAR2(255),
    imagem_banner    VARCHAR2(255),
    seguidores       NUMBER DEFAULT 0 CHECK (seguidores >= 0),
    verificado       NUMBER(1) DEFAULT 0 CHECK (verificado IN (0,1)),
    ativo            NUMBER(1) DEFAULT 1 CHECK (ativo IN (0,1)),
    data_criacao     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (genero_principal) REFERENCES genero_musical(id_genero),
    CHECK (tipo_artista IN ('individual','banda','grupo'))
);

-- ===============================================
-- 5. ÁLBUNS
-- ===============================================

CREATE TABLE IF NOT EXISTS album (
    id_album         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo           VARCHAR2(200) NOT NULL,
    tipo_album       VARCHAR2(20) NOT NULL,
    data_lancamento  DATE,
    duracao_total    NUMBER DEFAULT 0 CHECK (duracao_total >= 0),
    numero_faixas    NUMBER DEFAULT 0 CHECK (numero_faixas >= 0),
    gravadora        VARCHAR2(100),
    produtor         VARCHAR2(200),
    id_artista       NUMBER NOT NULL,
    genero_album     NUMBER,
    capa_album       VARCHAR2(255),
    preco            NUMBER(10,2),
    disponivel       NUMBER(1) DEFAULT 1 CHECK (disponivel IN (0,1)),
    explicito        NUMBER(1) DEFAULT 0 CHECK (explicito IN (0,1)),
    data_criacao     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (id_artista) REFERENCES artista(id_artista),
    FOREIGN KEY (genero_album) REFERENCES genero_musical(id_genero),
    CHECK (tipo_album IN ('studio','live','compilation','ep','single')),
    CHECK (preco IS NULL OR preco >= 0)
);

-- ===============================================
-- 6. MÚSICAS
-- ===============================================

CREATE TABLE IF NOT EXISTS musica (
    id_musica        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo           VARCHAR2(200) NOT NULL,
    duracao          NUMBER NOT NULL CHECK (duracao > 0 AND duracao <= 7200),
    id_album         NUMBER NOT NULL,
    numero_faixa     NUMBER,
    letra            CLOB,
    compositor       VARCHAR2(200),
    produtor         VARCHAR2(200),
    data_upload      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reproducoes      NUMBER(19) DEFAULT 0 CHECK (reproducoes >= 0),
    explicito        NUMBER(1) DEFAULT 0 CHECK (explicito IN (0,1)),
    disponivel       NUMBER(1) DEFAULT 1 CHECK (disponivel IN (0,1)),
    preview_url      VARCHAR2(255),
    arquivo_audio    VARCHAR2(255),
    
    FOREIGN KEY (id_album) REFERENCES album(id_album),
    UNIQUE (id_album, numero_faixa)
);

-- ===============================================
-- 7. PLAYLISTS
-- ===============================================

CREATE TABLE playlist (
    id_playlist      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_playlist    VARCHAR2(150) NOT NULL,
    descricao        VARCHAR2(500),
    publica          NUMBER(1) DEFAULT 0 CHECK (publica IN (0,1)),
    colaborativa     NUMBER(1) DEFAULT 0 CHECK (colaborativa IN (0,1)),
    data_criacao     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_modificacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario       NUMBER NOT NULL,
    numero_musicas   NUMBER DEFAULT 0 CHECK (numero_musicas >= 0),
    duracao_total    NUMBER DEFAULT 0 CHECK (duracao_total >= 0),
    imagem_capa      VARCHAR2(255),
    
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

-- ===============================================
-- 8. RELACIONAMENTO PLAYLIST-MÚSICA
-- ===============================================

CREATE TABLE playlist_musica (
    id_playlist_musica NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_playlist        NUMBER NOT NULL,
    id_musica          NUMBER NOT NULL,
    posicao            NUMBER NOT NULL CHECK (posicao > 0),
    data_adicao        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    adicionado_por     NUMBER,
    
    FOREIGN KEY (id_playlist) REFERENCES playlist(id_playlist) ON DELETE CASCADE,
    FOREIGN KEY (id_musica) REFERENCES musica(id_musica),
    FOREIGN KEY (adicionado_por) REFERENCES usuario(id_usuario),
    UNIQUE (id_playlist, posicao),
    UNIQUE (id_playlist, id_musica)
);

-- ===============================================
-- 9. VERIFICAR ESTRUTURAS CRIADAS
-- ===============================================

-- Mostrar todas as tabelas criadas
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
  AND table_type = 'BASE TABLE'
ORDER BY table_name;

-- Mostrar estrutura de uma tabela específica
-- DESC usuario; -- Oracle/MySQL
-- \d usuario     -- PostgreSQL

-- ===============================================
-- 10. DADOS DE EXEMPLO PARA TESTE
-- ===============================================

-- Inserir gêneros básicos
INSERT INTO genero_musical (id_genero, nome_genero, descricao, cor_tema) VALUES
(1, 'Rock', 'Gênero musical caracterizado por ritmo forte e guitarras', '#FF4444'),
(2, 'Pop', 'Música popular mainstream', '#44FF44'),
(3, 'Jazz', 'Gênero musical com improviso e harmonias complexas', '#4444FF'),
(4, 'Classical', 'Música clássica erudita', '#FFD700'),
(5, 'Electronic', 'Música eletrônica e dance', '#FF44FF');

-- Inserir um usuário de teste
INSERT INTO usuario (id_usuario, nome_usuario, sobrenome, email, genero, pais) 
VALUES (1, 'João', 'Silva', 'joao.silva@email.com', 'M', 'Brasil');

-- Inserir configuração do usuário
INSERT INTO configuracao_usuario (id_usuario) VALUES (1);

-- Inserir um artista de teste
INSERT INTO artista (id_artista, nome_artista, tipo_artista, pais_origem, genero_principal) 
VALUES (1, 'The Beatles', 'banda', 'Reino Unido', 1);

-- Inserir um álbum de teste
INSERT INTO album (id_album, titulo, tipo_album, data_lancamento, id_artista, genero_album) 
VALUES (1, 'Abbey Road', 'studio', '1969-09-26', 1, 1);

-- Inserir uma música de teste
INSERT INTO musica (id_musica, titulo, duracao, id_album, numero_faixa) 
VALUES (1, 'Come Together', 259, 1, 1);

-- Verificar dados inseridos
SELECT 'Dados de teste inseridos com sucesso!' as status;
