-- ===============================================
-- Estruturas Básicas - Sistema MusiStream
-- Módulo 04: Trabalhando com a Estrutura de Tabelas
-- ===============================================

-- Limpar estruturas anteriores se existirem
DROP TABLE IF EXISTS playlist_musica CASCADE CONSTRAINT;
DROP TABLE IF EXISTS playlist CASCADE CONSTRAINT;
DROP TABLE IF EXISTS musica CASCADE CONSTRAINT;
DROP TABLE IF EXISTS album CASCADE CONSTRAINT;
DROP TABLE IF EXISTS artista CASCADE CONSTRAINT;
DROP TABLE IF EXISTS genero_musical CASCADE CONSTRAINT;
DROP TABLE IF EXISTS usuario CASCADE CONSTRAINT;
DROP TABLE IF EXISTS configuracao_usuario CASCADE CONSTRAINT;

-- ===============================================
-- 1. USUÁRIOS
-- ===============================================

CREATE TABLE IF NOT EXISTS usuario (
    id_usuario       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_usuario     VARCHAR2(100) NOT NULL,
    sobrenome        VARCHAR2(100),
    nome_exibicao    VARCHAR2(150),
    email            VARCHAR2(254) NOT NULL UNIQUE,
    senha_hash       VARCHAR2(255) NOT NULL,
    data_nascimento  DATE,
    genero           CHAR(1),
    pais             VARCHAR2(50),
    idioma_pref      VARCHAR2(10) DEFAULT 'pt-BR',
    data_cadastro    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultima_atividade TIMESTAMP,
    ativo            NUMBER(1) DEFAULT 1 CHECK (ativo IN (0,1)),
    email_verificado NUMBER(1) DEFAULT 0 CHECK (email_verificado IN (0,1)),
    
    CHECK (genero IN ('M', 'F', 'O', 'N')),
    CHECK (LENGTH(nome_usuario) >= 2),
    CHECK (REGEXP_LIKE(email, '.+@.+\..+'))
);

COMMENT ON TABLE usuario IS 'Usuários registrados na plataforma MusiStream';

-- ===============================================
-- 2. CONFIGURAÇÕES DE USUÁRIO
-- ===============================================

CREATE TABLE IF NOT EXISTS configuracao_usuario (
    id_usuario        NUMBER PRIMARY KEY,
    tema              VARCHAR2(20) DEFAULT 'escuro',
    qualidade_audio   VARCHAR2(20) DEFAULT 'alta',
    volume_padrao     NUMBER DEFAULT 75 CHECK (volume_padrao BETWEEN 0 AND 100),
    reproducao_auto   NUMBER(1) DEFAULT 1 CHECK (reproducao_auto IN (0,1)),
    notificacoes      NUMBER(1) DEFAULT 1 CHECK (notificacoes IN (0,1)),
    modo_offline      NUMBER(1) DEFAULT 0 CHECK (modo_offline IN (0,1)),
    idioma_interface  VARCHAR2(10) DEFAULT 'pt-BR',
    
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    CHECK (tema IN ('claro','escuro','auto')),
    CHECK (qualidade_audio IN ('baixa','media','alta','lossless'))
);

-- ===============================================
-- 3. GÊNEROS MUSICAIS
-- ===============================================

CREATE TABLE IF NOT EXISTS genero_musical (
    id_genero       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_genero     VARCHAR2(50) NOT NULL UNIQUE,
    descricao       CLOB,
    genero_pai      NUMBER,
    cor_tema        VARCHAR2(7),
    icone           VARCHAR2(100),
    ativo           NUMBER(1) DEFAULT 1 CHECK (ativo IN (0,1)),
    
    FOREIGN KEY (genero_pai) REFERENCES genero_musical(id_genero),
    CHECK (LENGTH(nome_genero) >= 2),
    CHECK (cor_tema IS NULL OR REGEXP_LIKE(cor_tema, '^#[0-9A-Fa-f]{6}$'))
);

-- ===============================================
-- 4. ARTISTAS
-- ===============================================

CREATE TABLE IF NOT EXISTS artista (
    id_artista       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_artista     VARCHAR2(100) NOT NULL,
    tipo_artista     VARCHAR2(20) NOT NULL,
    biografia        CLOB,
    data_formacao    DATE,
    data_fim         DATE,
    pais_origem      VARCHAR2(50),
    cidade_origem    VARCHAR2(100),
    genero_principal NUMBER,
    website          VARCHAR2(255),
    instagram        VARCHAR2(100),
    twitter          VARCHAR2(100),
    facebook         VARCHAR2(255),
    spotify_id       VARCHAR2(50),
    imagem_perfil    VARCHAR2(255),
    imagem_banner    VARCHAR2(255),
    seguidores       NUMBER DEFAULT 0 CHECK (seguidores >= 0),
    verificado       NUMBER(1) DEFAULT 0 CHECK (verificado IN (0,1)),
    ativo            NUMBER(1) DEFAULT 1 CHECK (ativo IN (0,1)),
    data_criacao     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (genero_principal) REFERENCES genero_musical(id_genero),
    CHECK (tipo_artista IN ('individual','banda','grupo'))
);

-- ===============================================
-- 5. ÁLBUNS
-- ===============================================

CREATE TABLE IF NOT EXISTS album (
    id_album         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo           VARCHAR2(200) NOT NULL,
    tipo_album       VARCHAR2(20) NOT NULL,
    data_lancamento  DATE,
    duracao_total    NUMBER DEFAULT 0 CHECK (duracao_total >= 0),
    numero_faixas    NUMBER DEFAULT 0 CHECK (numero_faixas >= 0),
    gravadora        VARCHAR2(100),
    produtor         VARCHAR2(200),
    id_artista       NUMBER NOT NULL,
    genero_album     NUMBER,
    capa_album       VARCHAR2(255),
    preco            NUMBER(10,2),
    disponivel       NUMBER(1) DEFAULT 1 CHECK (disponivel IN (0,1)),
    explicito        NUMBER(1) DEFAULT 0 CHECK (explicito IN (0,1)),
    data_criacao     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (id_artista) REFERENCES artista(id_artista),
    FOREIGN KEY (genero_album) REFERENCES genero_musical(id_genero),
    CHECK (tipo_album IN ('studio','live','compilation','ep','single')),
    CHECK (preco IS NULL OR preco >= 0)
);

-- ===============================================
-- 6. MÚSICAS
-- ===============================================

CREATE TABLE IF NOT EXISTS musica (
    id_musica        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo           VARCHAR2(200) NOT NULL,
    duracao          NUMBER NOT NULL CHECK (duracao > 0 AND duracao <= 7200),
    id_album         NUMBER NOT NULL,
    numero_faixa     NUMBER,
    letra            CLOB,
    compositor       VARCHAR2(200),
    produtor         VARCHAR2(200),
    data_upload      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reproducoes      NUMBER(19) DEFAULT 0 CHECK (reproducoes >= 0),
    explicito        NUMBER(1) DEFAULT 0 CHECK (explicito IN (0,1)),
    disponivel       NUMBER(1) DEFAULT 1 CHECK (disponivel IN (0,1)),
    preview_url      VARCHAR2(255),
    arquivo_audio    VARCHAR2(255),
    
    FOREIGN KEY (id_album) REFERENCES album(id_album),
    UNIQUE (id_album, numero_faixa)
);

-- ===============================================
-- 7. PLAYLISTS
-- ===============================================

CREATE TABLE playlist (
    id_playlist      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_playlist    VARCHAR2(150) NOT NULL,
    descricao        VARCHAR2(500),
    publica          NUMBER(1) DEFAULT 0 CHECK (publica IN (0,1)),
    colaborativa     NUMBER(1) DEFAULT 0 CHECK (colaborativa IN (0,1)),
    data_criacao     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_modificacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario       NUMBER NOT NULL,
    numero_musicas   NUMBER DEFAULT 0 CHECK (numero_musicas >= 0),
    duracao_total    NUMBER DEFAULT 0 CHECK (duracao_total >= 0),
    imagem_capa      VARCHAR2(255),
    
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

-- ===============================================
-- 8. RELACIONAMENTO PLAYLIST-MÚSICA
-- ===============================================

CREATE TABLE playlist_musica (
    id_playlist_musica NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_playlist        NUMBER NOT NULL,
    id_musica          NUMBER NOT NULL,
    posicao            NUMBER NOT NULL CHECK (posicao > 0),
    data_adicao        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    adicionado_por     NUMBER,
    
    FOREIGN KEY (id_playlist) REFERENCES playlist(id_playlist) ON DELETE CASCADE,
    FOREIGN KEY (id_musica) REFERENCES musica(id_musica),
    FOREIGN KEY (adicionado_por) REFERENCES usuario(id_usuario),
    UNIQUE (id_playlist, posicao),
    UNIQUE (id_playlist, id_musica)
);

-- ===============================================
-- 9. VERIFICAR ESTRUTURAS CRIADAS
-- ===============================================

-- Mostrar todas as tabelas criadas
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
  AND table_type = 'BASE TABLE'
ORDER BY table_name;

-- Mostrar estrutura de uma tabela específica
-- DESC usuario; -- Oracle/MySQL
-- \d usuario     -- PostgreSQL

-- ===============================================
-- 10. DADOS DE EXEMPLO PARA TESTE
-- ===============================================

-- Descrever a tabela
-- DESCRIBE nome_tabela; -- Oracle/MySQL
DESCRIBE ARTISTA;

-- Inserir gêneros básicos
INSERT INTO usuario (nome_usuario, sobrenome, email, genero, pais, senha_hash) VALUES
('João', 'Silva', 'joaosilva@email.com', 'M', 'Brasil','hash1'),
('Maria', 'Oliveira', 'maria.oliveira@email.com', 'F', 'Brasil','hash2'),
('Pedro', 'Almeida', 'pedro.almeida@email.com', 'M', 'Portugal','hash3'),
('Ana', 'Costa', 'ana.costa@email.com', 'F', 'Brasil','hash4'),
('Lucas', 'Pereira', 'lucas.pereira@email.com', 'M', 'Brasil','hash5');

-- Inserir configuração do usuário
INSERT INTO configuracao_usuario 
(id_usuario, tema, qualidade_audio, volume_padrao, 
    reproducao_auto, notificacoes, modo_offline, 
    idioma_interface) 
VALUES
(1, 'escuro', 'alta', 75, 1, 1, 0, 'pt-BR'),
(2, 'claro', 'media', 50, 1, 1, 0, 'pt-BR'),
(3, 'auto', 'alta', 80, 1, 0, 1, 'pt-PT'),
(4, 'escuro', 'lossless', 60, 0, 1, 0, 'pt-BR'),
(5, 'claro', 'baixa', 70, 1, 1, 0, 'pt-BR');

-- Inserir artistas
INSERT INTO artista (nome_artista, tipo_artista, pais_origem, genero_principal) VALUES
('The Beatles', 'banda', 'Reino Unido', 1),
('Taylor Swift', 'individual', 'EUA', 2),
('Miles Davis', 'individual', 'EUA', 3),
('AC/DC', 'banda', 'Austrália', 4),
('BTS', 'grupo', 'Coreia do Sul', 5);

-- Inserir gêneros musicais
INSERT INTO genero_musical (id_genero, nome_genero, descricao, cor_tema) VALUES
(1, 'Rock', 'Gênero musical caracterizado por ritmo forte e guitarras', '#FF4444'),
(2, 'Pop', 'Música popular mainstream', '#44FF44'),
(3, 'Jazz', 'Gênero musical com improviso e harmonias complexas', '#4444FF'),
(4, 'Classical', 'Música clássica erudita', '#FFD700'),
(5, 'Electronic', 'Música eletrônica e dance', '#FF44FF');

-- Inserir álbuns
INSERT INTO album 
(titulo, tipo_album, data_lancamento, id_artista, genero_album, duracao_total, numero_faixas, preco) 
VALUES
('Abbey Road', 'studio', TO_DATE('1969-09-26','YYYY-MM-DD'), 1, 1, 2700, 17, 49.90),
('1989', 'studio', TO_DATE('2014-10-27','YYYY-MM-DD'), 2, 2, 3200, 13, 39.90),
('Kind of Blue', 'studio', TO_DATE('1959-08-17','YYYY-MM-DD'), 3, 3, 2800, 5, 59.90),
('Back in Black', 'studio', TO_DATE('1980-07-25','YYYY-MM-DD'), 4, 4, 2500, 10, 45.00),
('Map of the Soul: 7', 'studio', TO_DATE('2020-02-21','YYYY-MM-DD'), 5, 5, 2100, 20, 69.90);

-- Inserir músicas
INSERT INTO musica (titulo, duracao, id_album, numero_faixa) VALUES
('Come Together', 259, 1, 2),
('Something', 182, 1, 2),
('Blank Space', 231, 2, 1),
('Style', 231, 2, 2),
('So What', 545, 3, 1),
('Freddie Freeloader', 589, 3, 2),
('Hells Bells', 312, 4, 1),
('Shoot to Thrill', 320, 4, 2),
('ON', 250, 5, 1),
('Black Swan', 260, 5, 2);

-- Inserir playlists
INSERT INTO playlist 
(nome_playlist, descricao, publica, colaborativa, id_usuario) VALUES
('Rock Clássico', 'Grandes hits do rock', 1, 0, 1),
('Pop Hits', 'Top pop do momento', 1, 1, 2),
('Jazz Relax', 'Para relaxar', 1, 0, 3),
('AC/DC Favorites', 'Melhores do AC/DC', 0, 0, 4),
('BTS Collection', 'Todos os hits do BTS', 1, 1, 5);

-- Inserir músicas nas playlists
INSERT INTO playlist_musica 
(id_playlist, id_musica, posicao, adicionado_por) VALUES
(1, 1, 1, 1),
(1, 2, 2, 1),
(2, 3, 1, 2),
(2, 4, 2, 2),
(3, 5, 1, 3),
(3, 6, 2, 3),
(4, 7, 1, 4),
(4, 8, 2, 4),
(5, 9, 1, 5),
(5, 10, 2, 5);

-- Verificar dados inseridos
SELECT 'Dados de teste inseridos com sucesso!' as status;

-- Selecionar dados de todas as tabelas criadas

-- Tabela usuario
SELECT * FROM usuario;

-- Tabela configuracao_usuario
SELECT * FROM configuracao_usuario;

-- Tabela genero_musical
SELECT * FROM genero_musical;

-- Tabela artista
SELECT * FROM artista;

-- Tabela album
SELECT * FROM album;

-- Tabela musica
SELECT * FROM musica;

-- Tabela playlist
SELECT * FROM playlist;

-- Tabela playlist_musica
SELECT * FROM playlist_musica;

-- Inner join entre usuario e configuracao_usuario
SELECT u.nome_usuario, u.email, c.tema, c.qualidade_audio
FROM usuario u
INNER JOIN configuracao_usuario c ON u.id_usuario = c.id_usuario;

-- Inner join entre artista e genero_musical
SELECT a.nome_artista, g.nome_genero
FROM artista a
INNER JOIN genero_musical g ON a.genero_principal = g.id_genero;

-- Inner join entre album e artista
SELECT al.titulo AS album_titulo, ar.nome_artista
FROM album al
INNER JOIN artista ar ON al.id_artista = ar.id_artista;

-- Inner join entre musica e album
SELECT m.titulo AS musica_titulo, al.titulo AS album_titulo
FROM musica m
INNER JOIN album al ON m.id_album = al.id_album;

-- Inner join entre playlist e usuario
SELECT p.nome_playlist, u.nome_usuario
FROM playlist p
INNER JOIN usuario u ON p.id_usuario = u.id_usuario;

-- Inner join entre playlist_musica e musica
SELECT pm.id_playlist, m.titulo AS musica_titulo, pm.posicao
FROM playlist_musica pm
INNER JOIN musica m ON pm.id_musica = m.id_musica;

-- Inner join entre playlist_musica, playlist e usuario
SELECT pl.nome_playlist, u.nome_usuario, m.titulo AS musica_titulo
FROM playlist_musica pm
INNER JOIN playlist pl ON pm.id_playlist = pl.id_playlist
INNER JOIN usuario u ON pl.id_usuario = u.id_usuario
INNER JOIN musica m ON pm.id_musica = m.id_musica;