DECLARE
   v_ID SEGMERCADO.ID%type := 2;
   v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Atacado';
BEGIN
   INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, upper(v_DESCRICAO));
   COMMIT;
END;

SELECT * FROM SEGMERCADO WHERE DESCRICAO = 'ATACADO'
SELECT * FROM SEGMERCADO WHERE DESCRICAO = 'atacado'
DELETE FROM SEGMERCADO WHERE ID = 2;